import os
import emoji


modulo = ""

while modulo != "0":
    os.system('cls')
    print("\033[1;31;45m--------------------------------\033[m")
    print("\033[1;31;45m|           Py WOMAN           |\033[m")
    print("\033[1;31;45m--------------------------------\033[m")
    print(f"|| 1- Clientes {emoji.emojize(':bust_in_silhouette:')}             ||")
    print(f"|| 2- Produtos {emoji.emojize(':sh1opping_bags:')}              ||")
    print(f"|| 3- Vendas {emoji.emojize(':dollar_banknote:')}               ||")
    print(f"|| 4- Relatórios {emoji.emojize(':page_facing_up:')}           ||")
    print(f"|| 5- Sobre o sistema {emoji.emojize(':desktop_computer:')}       ||")
    print(f"\\\ 0- Sair {emoji.emojize(':BACK_arrow:')}                 //")
    print("  -----------------------------")
    modulo = input("Informe o módulo que deseja acessar: ").strip()
    while not(modulo in "123450"):
        modulo = input("Informe uma opção válida: ").strip()
    if modulo == "1":
        os.system('cls')
        print("\033[1;31;45m--------------------------------\033[m")
        print("\033[1;31;45m|      MÓDULO DE CLIENTES      |\033[m")
        print("\033[1;31;45m--------------------------------\033[m")
        print(f"|| 1- Cadastrar cliente {emoji.emojize(':check_mark_button:')}    ||")
        print(f"|| 2- Ver dados do cliente{emoji.emojize(':page_facing_up:')}  ||")
        print(f"|| 3- Atualizar dados{emoji.emojize(':clockwise_vertical_arrows:')}       ||")
        print(f"|| 4- Excluir cadastro {emoji.emojize(':wastebasket:')}      ||")
        print(f"\\\ 0- Voltar {emoji.emojize(':BACK_arrow:')}               //")
        print("  ----------------------------")
        resp1 = input("Informe a opção que deseja: ").strip()
        while not(resp1 in "12340"):
            resp1 = input("Informe uma opção válida: ").strip()
        if resp1 == "1":
            os.system('cls')
            print("\033[1;31;45m--------------------------------\033[m")
            print("\033[1;31;45m|      CADASTRAR CLIENTE       |\033[m")
            print("\033[1;31;45m--------------------------------\033[m")
            print()
            nome = input("Informe o nome do cliente: ").strip()
            idade = input("Informe a idade do cliente: ").strip()
            fone = input("Informe o número do telefone do cliente: ").strip()
            cpf = input("Informe o CPF do cliente: ").strip()
            print("--------------------------------")
            print(f"|      CLIENTE CADASTRADO {emoji.emojize(':check_mark_button:')}   |")
            print("--------------------------------")
            print()
            print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
            print("Isso é apenas uma simulação")
            print("Essa função ainda está em desenvolvimento!")
            print()
            input('APERTE ENTER PARA PROSSEGUIR')
        elif resp1 == "2":
            os.system('cls')
            print("\033[1;31;45m--------------------------------\033[m")
            print(f"\033[1;31;45m|       DADOS DO CLIENTE{emoji.emojize(':page_facing_up:')}     |\033[m")
            print("\033[1;31;45m--------------------------------\033[m")
            print()
            cpf = input("CPF: ").strip()
            print()
            print("NOME: NOME DO CLIENTE")
            print(f"CPF: {cpf}")
            print("TELEFONE: (XX)ZZZZZYYYY")
            print("IDADE: X ANOS")
            print()
            print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
            print("Isso é apenas uma simulação")
            print("Essa função ainda está em desenvolvimento!")
            input('APERTE ENTER PARA PROSSEGUIR')
        elif resp1 == "3":
            os.system('cls')
            print("\033[1;31;45m--------------------------------\033[m")
            print("\033[1;31;45m|       ATUALIZAR DADOS        |\033[m")
            print("\033[1;31;45m--------------------------------\033[m")
            print()
            cpf = input("CPF: ").strip()
            print()
            nome = input("Informe o novo nome para o cliente: ").strip()
            idade = input("Informe a nova idade para cliente: ").strip()
            fone = input("Informe o novo número telefone cliente: ").strip()
            cpf = input("Informe o novo CPF do cliente: ").strip()
            print()
            print("--------------------------------")
            print(f"|      DADOS ATUALIZADOS{emoji.emojize(':warning:')}     |")
            print("--------------------------------")
            print()
            print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
            print("Isso é apenas uma simulação")
            print("Essa função ainda está em desenvolvimento!")
            input('APERTE ENTER PARA PROSSEGUIR')
        elif resp1 == "4":
            os.system('cls')
            print("\033[1;31;45m--------------------------------\033[m")
            print(f"\033[1;31;45m|        EXCLUIR CADASTRO {emoji.emojize(':wastebasket:')}    |\033[m")
            print("\033[1;31;45m--------------------------------\033[m")
            print()
            cpf = input("CPF: ").strip()
            print()
            print("--------------------------------")
            print(f"|      CADASTRO EXCLUÍDO{emoji.emojize(':warning:')}    |")
            print("--------------------------------")
            print()
            print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
            print("Isso é apenas uma simulação")
            print("Essa função ainda está em desenvolvimento!")
            input('APERTE ENTER PARA PROSSEGUIR')
    elif modulo == "2":
        os.system('cls')
        print("\033[1;31;45m--------------------------------\033[m")
        print("\033[1;31;45m|      MÓDULO DE PRODUTOS      |\033[m")
        print("\033[1;31;45m--------------------------------\033[m")
        print(f"|| 1- Roupas{emoji.emojize(':dress:')}                ||")
        print(f"|| 2- Cosméticos{emoji.emojize(':lipstick:')}             ||")
        print(f"\\\ 3- Acessórios{emoji.emojize(':sunglasses:')}            //")
        print("  ----------------------------")
        resp2 = input("Informe a opção que deseja: ").strip()
        while not(resp2 in "123"):
            resp2 = input("Informe uma opção válida: ").strip()
        if resp2 == "1":
            os.system('cls')
            print("\033[1;31;45m------------------------------------\033[m")
            print("\033[1;31;45m|         ROUPAS FEMININA          |\033[m")
            print("\033[1;31;45m------------------------------------\033[m")
            print(f"|| 1- Cadastrar peça de roupa{emoji.emojize(':check_mark_button:')}   ||")
            print(f"|| 2- Ver informações da peça{emoji.emojize(':page_facing_up:')}   ||")
            print(f"|| 3- Editar informações da peça{emoji.emojize(':clockwise_vertical_arrows:')}||")
            print(f"|| 4- Excluir peça{emoji.emojize(':wastebasket:')}               ||")
            print(f"\\\ 0- Voltar{emoji.emojize(':BACK_arrow:')}                    //")
            print("   ------------------------------")
            resp3 = input("Informe a opção que deseja: ").strip()
            while not(resp3 in "12340"):
                resp3 = input("Informe uma opção válida: ").strip()
            if resp3 == "1":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|       CADASTRAR PEÇA         |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                tipo_peça = input("Informe o tipo de peça: ").strip()
                tamanho = input("Informe o tamanho da peça: ").strip()
                codigo = input("Informe o código da peça: ").strip()
                cor = input("Informe a cor da peça: ").strip()
                preco = input("Informe o valor da peça: R$").strip()
                print()
                print("--------------------------------")
                print(f"|       PEÇA CADASTRADA{emoji.emojize(':check_mark_button:')}      |")
                print("--------------------------------")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                print()
                input('APERTE ENTER PARA PROSSEGUIR')
            elif resp3 == "2":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|        DADOS DA PEÇA         |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                codigo = input("Informe o código da peça: ").strip()
                print()
                print("TIPO: TIPO DA PEÇA")
                print(f"CÓDIGO: {codigo}")
                print("TAMANHO: P,M,G")
                print("COR: AMARELO(EXEMPLO)")
                print("PREÇO: R$XXX")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                input('APERTE ENTER PARA PROSSEGUIR')
            elif resp3 == "3":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|       ATUALIZAR PEÇA         |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                codigo = input("Informe o código da peça: ").strip()
                print()
                codigo = input("Informe o novo código para a peça: ").strip()
                cor = input("Informe a cor atualizada da peça: ").strip()
                tipo_peça = input("Informe o tipo atualizado da peça: ").strip()
                tamanho = input("Informe o tamanho atualizado da peça: ").strip()
                preco = input("Informe o novo valor da peça: R$").strip()
                print()
                print("--------------------------------")
                print(f"|       PEÇA ATUALIZADA{emoji.emojize(':check_mark_button:')}       |")
                print("--------------------------------")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                input('APERTE ENTER PARA PROSSEGUIR')
            elif resp3 == "4":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|         EXCLUIR PEÇA         |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                codigo = input("CÓDIGO: ").strip()
                print()
                print("--------------------------------")
                print(f"|        PEÇA EXCLUÍDA{emoji.emojize(':check_mark_button:')}        |")
                print("--------------------------------")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                input('APERTE ENTER PARA PROSSEGUIR')
        elif resp2 == "2":
            print("\033[1;31;45m-----------------------------------\033[m")
            print("\033[1;31;45m|       COSMÉTICOS FEMININOS      |\033[m")
            print("\033[1;31;45m-----------------------------------\033[m")
            print(f"|| 1- Cadastrar cosméticos{emoji.emojize(':check_mark_button:')}      ||")
            print(f"|| 2- Dados do cosmético{emoji.emojize(':page_facing_up:')}         ||")
            print(f"|| 3- Editar dados do cosmético{emoji.emojize(':clockwise_vertical_arrows:')}  ||")
            print(f"|| 4- Excluir cosmético{emoji.emojize(':wastebasket:')}         ||")
            print(f"\\\ 0- Voltar{emoji.emojize(':BACK_arrow:')}                   // ")
            print("  -------------------------------")
            resp4 = input('Informe a opção que deseja: ').strip()
            while not(resp4 in "12340"):
                resp4 = input("Informe uma opção válida: ").strip()
            if resp4 == "1":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|     CADASTRAR COSMÉTICOS     |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                tipo_cosmético = input("Informe o tipo do cosmético: ").strip()
                codigo = input("Informe o código do cosméstico: ").strip()
                preco = input("Informe o valor do cosmético: R$").strip()
                print()
                print("--------------------------------")
                print(f"|     COSMÉTICO CADASTRADO{emoji.emojize(':check_mark_button:')}    |")
                print("--------------------------------")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                print()
                input('APERTE ENTER PARA PROSSEGUIR')
            elif resp4 == "2":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|      DADOS DO COSMÉTICO      |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                codigo = input("Informe o código do cosmético: ").strip()
                print()
                print("TIPO: TIPO DO COSMÉTICO")
                print(f"CÓDIGO: {codigo}")
                print("PREÇO: R$XXX")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                input('APERTE ENTER PARA PROSSEGUIR')
            elif resp4 == "3":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|         EDITAR DADOS         |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                codigo = input("Informe o código do cosmético: ").strip()
                print()
                tipo_cosmético = input("Informe o tipo atualizado da cosmético: ").strip()
                preco = input("Informe o novo valor para o cosmético: R$").strip()
                
                print()
                print("--------------------------------")
                print(f"|       DADOS ATUALIZADOS{emoji.emojize(':check_mark_button:')}    |")
                print("--------------------------------")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                input('APERTE ENTER PARA PROSSEGUIR')
            elif resp4 == "4":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|       EXCLUÍR COSMÉTICO      |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                codigo = input("CÓDIGO: ").strip()
                print()
                print("--------------------------------")
                print(f"|      COSMÉTICO EXCLUÍDO{emoji.emojize(':check_mark_button:')}    |")
                print("--------------------------------")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                input('APERTE ENTER PARA PROSSEGUIR')
        elif resp2 == "3":
            print("\033[1;31;45m-----------------------------------\033[m")
            print("\033[1;31;45m|       ACESSÓRIOOS FEMININOS     |\033[m")
            print("\033[1;31;45m-----------------------------------\033[m")
            print(f"|| 1- Cadastrar acessório{emoji.emojize(':check_mark_button:')}       ||")
            print(f"|| 2- Dados do acessório{emoji.emojize(':page_facing_up:')}        ||")
            print(f"|| 3- Editar dados do acessório{emoji.emojize(':clockwise_vertical_arrows:')} ||")
            print(f"|| 4- Excluir acessório{emoji.emojize(':wastebasket:')}         ||")
            print(f"\\\ 0- Voltar{emoji.emojize(':BACK_arrow:')}                   //")
            print("  ------------------------------")
            resp5 = input('Informe a opção que deseja: ').strip()
            while not(resp5 in "12340"):
                resp5 = input("Informe uma opção válida: ").strip()
            if resp5 == "1":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|     CADASTRAR ACESSÓRIO      |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                tipo_acessorio = input("Informe o tipo do acessório: ").strip()
                codigo = input("Informe o código do acessório: ").strip()
                preco = input("Informe o valor do acessório: R$").strip()
                print()
                print("--------------------------------")
                print(f"|     ACESSÓRIO CADASTRADO{emoji.emojize(':check_mark_button:')}   |")
                print("--------------------------------")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                print()
                input('APERTE ENTER PARA PROSSEGUIR')
            elif resp5 == "2":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|      DADOS DO ACESSÓRIO      |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                codigo = input("Informe o código do acessório: ").strip()
                print()
                print("TIPO: TIPO DO ACESSÓRIO")
                print(f"CÓDIGO: {codigo}")
                print("PREÇO: R$XXX")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                input('APERTE ENTER PARA PROSSEGUIR')
            elif resp5 == "3":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|        EDITAR DADOS          |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                codigo = input("Informe o código do acessório: ").strip()
                print()
                tipo_acessorio = input("Informe o tipo atualizado da acessório: ").strip()
                preco = input("Informe o novo valor para o acessório: R$").strip()
                print()
                print("--------------------------------")
                print(f"|       DADOS ATUALIZADOS{emoji.emojize(':check_mark_button:')}    |")
                print("--------------------------------")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                input('APERTE ENTER PARA PROSSEGUIR')
            elif resp5 == "4":
                os.system('cls')
                print("\033[1;31;45m--------------------------------\033[m")
                print("\033[1;31;45m|      EXCLUIR ACESSÓRIO       |\033[m")
                print("\033[1;31;45m--------------------------------\033[m")
                print()
                codigo = input("CÓDIGO: ").strip()
                print()
                print("--------------------------------")
                print(f"|      ACESSÓRIO EXCLUÍDO{emoji.emojize(':check_mark_button:')}    |")
                print("--------------------------------")
                print()
                print(f"     \033[1;33mATENÇÃO!\033[m{emoji.emojize(':warning:')}  ")
                print("Isso é apenas uma simulação")
                print("Essa função ainda está em desenvolvimento!")
                input('APERTE ENTER PARA PROSSEGUIR')
    elif modulo == "3":
        os.system('cls')
        print("\033[1;31;45m-----------------------------------\033[m")
        print("\033[1;31;45m|          MÓDULO DE VENDAS       |\033[m")
        print("\033[1;31;45m-----------------------------------\033[m")
        print(f"|| 1- Adionar venda{emoji.emojize(':check_mark_button:')}            ||")
        print(f"|| 2- Vizualizar vendas{emoji.emojize(':page_facing_up:')}        ||")
        print(f"|| 3- Editar venda{emoji.emojize(':clockwise_vertical_arrows:')}             ||")
        print(f"|| 4- Excluir uma venda{emoji.emojize(':wastebasket:')}         ||")
        print(f"\\\ 0- Voltar{emoji.emojize(':BACK_arrow:')}                   //")
        print("  -------------------------------")
        resp6 = input("Informe a opção desejada: ").strip()
        while not(resp6 in "12340"):
                resp6 = input("Informe uma opção válida: ").strip()
        if resp6 != "0":
            print()
            print("\033[1;31;45m-----------------------------------\033[m")
            print(f"\033[1;31;45m|    FUNÇÃO EM DESENVOLVIMENTO{emoji.emojize(':warning:')}   |\033[m")
            print("\033[1;31;45m-----------------------------------\033[m")
            print()
            input('APERTE ENTER PARA PROSSEGUIR')
    elif modulo == "4":
        os.system('cls')
        print("\033[1;31;45m-----------------------------------\033[m")
        print("\033[1;31;45m|        MÓDULO DE RELATÓTIOS     |\033[m")
        print("\033[1;31;45m-----------------------------------\033[m")
        print("|| 1- Lista dos produtos         ||")
        print("|| 2- Lista de vendas            ||")
        print("|| 3- Lista de clientes          ||")
        print("|| 4- Produtos mais vendidos     ||")
        print("|| 5- Preferência de clientes    ||")
        print("\\\ 0- Voltar                    //")
        print("  -------------------------------")
        resp7 = input("Informe a opção desejada: ").strip()
        while not(resp7 in "123450"):
            resp7 = input("Informe uma opção válida: ").strip()
        if resp7 != "0":
            print()
            print("\033[1;31;45m-----------------------------------\033[m")
            print(f"\033[1;31;45m|    FUNÇÃO EM DESENVOLVIMENTO{emoji.emojize(':warning:')}   |\033[m")
            print("\033[1;31;45m-----------------------------------\033[m")
            print()
            input('APERTE ENTER PARA PROSSEGUIR')
    elif modulo == "5":
        print("\033[1;31;45m-------------------------------------------\033[m")
        print("\033[1;31;45m|               SOBRE O SISTEMA           |\033[m")
        print("\033[1;31;45m-------------------------------------------\033[m")
        print("|| PROGRAMA PARA GESTÃO DE LOJA FEMININA ||")
        print("||           DESENVOLVIDO POR:           ||")
        print("|| 1- hadrianus.lima.130@ufrn.edu.br     ||")
        print("||              LICENÇA MIT              ||")
        print("||  https://opensource.org/licenses/MIT  ||")
        print("\\\                                       //")
        print("  ---------------------------------------")
        input('APERTE ENTER PARA PROSSEGUIR')


print("PROGRAMA FECHADO")
